services:
  db:
    image: nouchka/sqlite3:latest
    volumes:
      - db_data:/var/lib/sqlite/
    restart: on-failure
    env_file:
      - ./.env

  bot:
    build: .
    command: sh -c "python -m main"
    volumes:
      - .dairy_db.sql:/var/lib/sqlite/
    env_file:
      - ./.env
    restart: always
    depends_on:
      - db

  volumes:
    db_data:
